server:
  port: 8051

dubbo:
  application:
    name: dubbo-nacos-springboot-provider
    qos-enable: false
  protocol:
    name: dubbo
    port: -1
  config-center:
    address: nacos://localhost:8848
    group: nacos-proj
  registry:
    address: nacos://localhost:8848
    group: nacos-proj

